app/assets/stylesheets/pages/_index.scss, app/controllers/poilus_controller.rb, app/views/poilus/index.html.erb, db/seeds.rb
Voila l'affichage des cartes pour chaque poilu, dites moi ce qu'il faut changer pls
=> Index poilu

app/models/booking.rb, app/models/poilu.rb
> added validations to Poilu model + Booking Model
=> added validations to models

app/controllers/poilus_controller.rb, app/views/poilus/show.html.erb
> added the method destroy in poilus controller
> added a delete link in views Show
> added an icon to back button
> added an icon to delete button
=> delete a poilu + add icons for back and delete

app/controllers/bookings_controller.rb, app/views/bookings/_form1.html.erb, app/views/bookings/_form2.html.erb, app/views/bookings/new.html.erb, app/views/bookings/pay.html.erb, app/views/poilus/show.html.erb, config/routes.rb, db/migrate/20200218101952_add_column_paid_to_booking.rb, db/schema.rb
Please check my code.
We can book a poilue and confirm the booking by pressing "pay" button
We can see the bookings only in our console
=> add booking and pay, doesn't show the bookings

app/views/layouts/application.html.erb, app/views/poilus/show.html.erb
Check this plsss, now we can see the booking on the poilu's view
=> see the bookings on the poilu's show/view

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/poilus_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/policies/poilu_policy.rb, app/views/poilus/show.html.erb, test/policies/booking_policy_test.rb, test/policies/poilu_policy_test.rb
ça marche bien chez moi mais j'ai dû faire beaucoup de modifs partout!!! donc on a 99% de chances d'avoir des conflicts!
=> adding pundit

app/controllers/bookings_controller.rb
Redirected pay-button to the view show of poilu-controller
=> redirected pay-button to view-show

app/views/bookings/_form1.html.erb, app/views/bookings/_form2.html.erb, app/views/poilus/show.html.erb, app/views/shared/_navbar.html.erb
I hope I didn't forget any english word :D
=> no more english text

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, db/migrate/20200219100220_add_usernamr_to_user.rb, db/schema.rb
Just added username to user, so now we can use @user.username :)
and also changes the sign-up form - it asks for a username
pls check all this
thx 
❤️
=> added username column to user table

app/assets/stylesheets/components/_form_container.scss, app/assets/stylesheets/components/_index.scss, app/views/poilus/_form.html.erb, app/views/poilus/new.html.erb
Form for new poilu, pls check and say me if not ok for u
=> new poilu form custimized

app/assets/stylesheets/components/_form_container.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> signin et singn up forms changed

app/views/poilus/_editform.html.erb
=> poilu edit form customized

app/assets/stylesheets/components/_form_container.scss, app/views/bookings/_form1.html.erb, app/views/bookings/_form2.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/poilus/_editform.html.erb, app/views/poilus/_form.html.erb
=> booking forms ok

app/models/poilu.rb
Now we can delete a poilu even if it has bookings
=> delete poilu with bookings

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/_index.scss, app/assets/stylesheets/users/_show.scss, app/controllers/application_controller.rb, app/controllers/user/confirmations_controller.rb, app/controllers/user/omniauth_callbacks_controller.rb, app/controllers/user/passwords_controller.rb, app/controllers/user/registrations_controller.rb, app/controllers/user/sessions_controller.rb, app/controllers/user/unlocks_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/layouts/application.html.erb, app/views/poilus/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb, test/policies/user_policy_test.rb
- double alert fixed
- profile page created
=> alert bug fixed, profile page created without image

app/views/poilus/show.html.erb
Rien a voir avec le nom, j'ai seulement effacé l'affichage des réservations dans la page show de poilu
=> no more booking in poilu view-show

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Lea touche plus à mes boutons

app/controllers/bookings_controller.rb, app/controllers/users_controller.rb, app/policies/booking_policy.rb, app/views/bookings/_editform1.html.erb, app/views/bookings/edit.html.erb, app/views/poilus/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb
J'ai ajjouté le "t" au appartient dans la view de poilu
J'ai affiché le username  dans la navbar
J'ai crée les methodes edit et delete de bookings(affichés dans la view user)
Desole pour le front :(
=> username dans la navbar, appartienT, booking edit et booking delete

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card_category.scss, app/assets/stylesheets/components/_navbar.scss, app/views/poilus/index.html.erb
> fixed dropdown menu issue
> designed dropdown menu
> designed cards 
> added a location and user
=> cards design

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
-on peux ajouter une image de profil quand on crée un nouveau profil
-photo avatar sur la navbar
=> profile picture

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/views/users/show.html.erb
> débroussaillage de la page profile
=> prep profile page

app/assets/stylesheets/pages/_show.scss, app/views/poilus/show.html.erb
> image responsive
> design des infos poilus
=> page description complete with img responsive
